version: "3"
services:
  postgres:
    image: postgres:15-bullseye
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: bezbednost
      POSTGRES_USER: bezbednost
      POSTGRES_DB: DB
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: bezbednost@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: bezbednost
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres-data:
  pgadmin:
